# 개발 환경에 맞춤
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trendythread?useSSL=false&serverTimezone=UTC
    username: {DEV_DB_USERNAME}
    password: {DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # 테이블 없으면 생성, 있으면 컬럼 변경
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: DEBUG
  file:
    path: var/logs/trendy-dev.log
#    name: logs/trendy-dev.log - 2.2에서 사용하던 버전


